export const tools = [
  {
    image: "/images/tools/python.png",
    link: "https://docs.python.org/3/",
    title: "Python",
    description: "High-level language for web development, data analysis, and AI",
  },
  {
    image: "/images/tools/java.png",
    link: "https://docs.oracle.com/en/java/",
    title: "Java",
    description: "Object-oriented language for enterprise and Android app development",
  },
  {
    image: "/images/tools/javascript.png",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    title: "JavaScript",
    description: "Client-side scripting language for web applications",
  },
  {
    image: "/images/tools/git.png",
    link: "https://git-scm.com/docs",
    title: "Git",
    description: "Version control system for collaborative software development",
  },
  {
    image: "/images/tools/github.png",
    link: "https://docs.github.com/en",
    title: "GitHub",
    description: "Cloud-based platform for collaborative software development",
  },
  {
    image: "/images/tools/bootstrap.png",
    link: "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
    title: "Bootstrap",
    description: "UI framework for responsive web design",
  },
  {
    image: "/images/tools/tailwindcss.png",
    link: "https://tailwindcss.com/docs/installation",
    title: "Tailwind CSS",
    description: "Utility-first CSS framework for rapid development",
  },
  {
    image: "/images/tools/react.png",
    link: "https://reactjs.org/docs/getting-started.html",
    title: "React",
    description: "JavaScript library for building user interfaces",
  },
  {
    image: "/images/tools/nextjs.png",
    link: "https://nextjs.org/docs/getting-started",
    title: "Next.js",
    description: "React-based framework for server-rendered web applications",
  },
  {
    image: "/images/tools/docker.png",
    link: "https://docs.docker.com/get-started/",
    title: "Docker",
    description: "Containerization platform for deploying applications",
  },
  {
    image: "/images/tools/mongodb.png",
    link: "https://docs.mongodb.com/manual/",
    title: "MongoDB",
    description: "NoSQL database for storing large amounts of data",
  },
  {
    image: "/images/tools/mysql.png",
    link: "https://dev.mysql.com/doc/",
    title: "MySQL",
    description: "Relational database management system",
  },
  {
    image: "/images/tools/spring.png",
    link: "https://spring.io/guides",
    title: "Spring",
    description: "Java-based framework for building enterprise applications",
  },
  {
    image: "/images/tools/redux.png",
    link: "https://redux.js.org/introduction/getting-started",
    title: "Redux",
    description: "State management library for JavaScript applications",
  },
  {
    image: "/images/tools/redis.png",
    link: "https://redis.io/documentation",
    title: "Redis",
    description: "In-memory data store for caching and session management",
  },
  {
    image: "/images/tools/postman.png",
    link: "https://learning.postman.com/docs/getting-started/introduction/",
    title: "Postman",
    description: "API testing tool for debugging and documentation",
  },
  {
    image: "/images/tools/djangorest.png",
    link: "https://www.django-rest-framework.org/",
    title: "Django REST framework",
    description: "Django-based framework for building RESTful APIs",
  },
];

